pipeline {
    agent {
        docker {
            image 'alpine'
            args '-u root:root'
            label 'jarvis'
        }
    }
    stages {
        stage('Deps') {
            steps {
                sh 'apk add git go'
                sh 'go get nhooyr.io/websocket'
                sh 'go get github.com/google/uuid'
            }
        }
        stage('Build server') {
            steps {
                sh 'cd server && go build'
            }
        }
    }
}
