pipeline {
    agent {
        docker {
            image 'alpine'
            args '-u root:root'
            label 'jarvis'
        }
    }
    stages {
        stage('Deps') {
            steps {
                sh 'apk add git go'
            }
        }
        stage('Build server') {
            steps {
                sh 'cd server && go build'
            }
        }
        stage('Test server') {
            steps {
                sh 'cd server && ./server &'
                sh 'sleep 3'
                sh 'cd server && go test'
            }
        }
    }
    post {
        unsuccessful {
            slackSend message: "${env.JOB_NAME} build #${env.BUILD_NUMBER} FAILED (<${env.RUN_DISPLAY_URL}|Open>)"
        }
    }
}
